[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
admin_passwd = $pbkdf2-sha512$600000$f28t5dzbO4fQmrP2nrMWAg$ZE1rNTPAJ.8Ta50QCUvJygZ4cmcMF.oo8Foe7JNdySsbchpK.U1LWGz5XaLNqXeI8V4HTE8FB.qn6vxaIqmkDA
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
proxy_mode = False

